import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'pages/login_page.dart';
import 'pages/registration_page.dart'; // Add this import
import 'firebase_options.dart'; // if you used flutterfire configure; otherwise remove and use Firebase.initializeApp()

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // If you have firebase_options.dart generated by flutterfire, use below:
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // If you don't have firebase_options.dart, use: await Firebase.initializeApp();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SAFORA',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.pink),
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginPage(),
        '/register': (context) => const RegisterPage(), // Add register route
      },
      home: const LoginPage(), // Fallback
    );
  }
}